org: thehecktour
app: vagasayajinbot
service: vagaSayajinbot

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1

functions:
  app:
    handler: app.app
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: '{proxy+}'
          method: any
          cors: true
