org: vagaSayajinBot
app: vagaSayajinBot
service: vagaSayajinBot

provider:
  name: aws
  runtime: nodejs18.x

functions:
  app:
    handler: app.app
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: '{proxy+}'
          method: any
          cors: true
